### ISSUE TITLE
Content div off-centered on iPad?

### ISSUE THREAD

**Issue by pimoore** [cdevroe/redoak-microblog#1]
Hi Colin,

Safari and Inspect browsers on iPadOS are both displaying the content div skewed to the right of the screen (screenshots attached for portrait and landscape mode).

Cheers!
-Pete
![AD87A864-E0BF-4479-853D-E94242C5E6E8](https://user-images.githubusercontent.com/5413470/114631846-61cacd00-9c8b-11eb-9e9a-aad0588c87e4.png)
![061551FB-EB27-490D-B722-B490749E95B9](https://user-images.githubusercontent.com/5413470/114631847-62fbfa00-9c8b-11eb-8f2e-42fdc62461cd.png)

**Comment by cdevroe** [comment]
@pimoore Thank you for reporting!
