### ISSUE TITLE
Text superimposed in footer

### ISSUE THREAD

**Issue by pimoore** [cdevroe/redoak-microblog#4]
Hi Colin,

The padding for the footer info needs to be increased a bit.

Cheers,
-Pete

![AED1849F-9FD4-45F7-9D44-ECB154E74C48](https://user-images.githubusercontent.com/5413470/115322167-65f75e80-a153-11eb-82f4-6c4b4b836318.jpeg)

**Comment by cdevroe** [comment]
@pimoore Thank you for reporting this issue. It will be fixed in the next release.
